
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Oct 21 22:28:21 CDT 2022
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AS = 77;
  public static final int IDENTIFICADOR = 31;
  public static final int PARIZQ = 3;
  public static final int FROM = 75;
  public static final int TYPEOF = 61;
  public static final int PTCOMA = 2;
  public static final int TYPE = 74;
  public static final int IMPLEMENTS = 78;
  public static final int RMIENTRAS = 26;
  public static final int CONST = 36;
  public static final int EXPORT = 43;
  public static final int GET = 69;
  public static final int RELSE = 29;
  public static final int CONSTRUCTOR = 67;
  public static final int ENUM = 42;
  public static final int REQUIRE = 71;
  public static final int CATCH = 33;
  public static final int THROW = 58;
  public static final int RIF = 28;
  public static final int COMILLA_SIMPLE = 9;
  public static final int NIGUALQUE = 20;
  public static final int POR = 13;
  public static final int DECLARE = 68;
  public static final int YIELD = 85;
  public static final int PROTECTED = 82;
  public static final int FALSE = 45;
  public static final int MENQUE = 17;
  public static final int VAR = 62;
  public static final int DOS_PUNTOS = 7;
  public static final int PACKAGE = 80;
  public static final int MAYQUE = 18;
  public static final int CLASS = 35;
  public static final int DIVIDIDO = 14;
  public static final int COMA = 10;
  public static final int SUPER = 55;
  public static final int ENTERO = 21;
  public static final int TRUE = 59;
  public static final int IGUAL = 30;
  public static final int MASMAS = 16;
  public static final int EXTENDS = 44;
  public static final int MODULE = 70;
  public static final int DELETE = 40;
  public static final int DECIMAL = 22;
  public static final int BOOLEAN = 66;
  public static final int LLAVDER = 6;
  public static final int SWITCH = 56;
  public static final int DO = 41;
  public static final int FOR = 47;
  public static final int VOID = 63;
  public static final int PUBLIC = 83;
  public static final int RETURN = 54;
  public static final int PARDER = 4;
  public static final int CONCAT = 15;
  public static final int TRY = 60;
  public static final int MENOS = 12;
  public static final int MAS = 11;
  public static final int BREAK = 34;
  public static final int NULL = 52;
  public static final int EOF = 0;
  public static final int PUNTO = 8;
  public static final int THIS = 57;
  public static final int DEFAULT = 39;
  public static final int FUNCTION = 48;
  public static final int IMPORT = 49;
  public static final int RNUMERO = 27;
  public static final int DEBUGGER = 38;
  public static final int IGUALQUE = 19;
  public static final int IN = 50;
  public static final int SET = 72;
  public static final int error = 1;
  public static final int FINALLY = 46;
  public static final int CONTINUE = 37;
  public static final int INSTANCEOF = 51;
  public static final int OF = 76;
  public static final int UMENOS = 24;
  public static final int ANY = 65;
  public static final int CASE = 32;
  public static final int CADENA = 23;
  public static final int NEW = 53;
  public static final int STRING = 73;
  public static final int PRIVATE = 81;
  public static final int STATIC = 84;
  public static final int LET = 79;
  public static final int WITH = 64;
  public static final int RIMPRIMIR = 25;
  public static final int LLAVIZQ = 5;
}

