
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Oct 16 20:48:35 CDT 2022
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AS = 76;
  public static final int IDENTIFICADOR = 30;
  public static final int PARIZQ = 3;
  public static final int FROM = 74;
  public static final int TYPEOF = 60;
  public static final int PTCOMA = 2;
  public static final int TYPE = 73;
  public static final int IMPLEMENTS = 77;
  public static final int RMIENTRAS = 25;
  public static final int CONST = 35;
  public static final int EXPORT = 42;
  public static final int GET = 68;
  public static final int RELSE = 28;
  public static final int CONSTRUCTOR = 66;
  public static final int ENUM = 41;
  public static final int CATCH = 32;
  public static final int REQUIRE = 70;
  public static final int THROW = 57;
  public static final int RIF = 27;
  public static final int COMILLA_SIMPLE = 9;
  public static final int NIGUALQUE = 19;
  public static final int POR = 13;
  public static final int DECLARE = 67;
  public static final int YIELD = 84;
  public static final int PROTECTED = 81;
  public static final int FALSE = 44;
  public static final int MENQUE = 16;
  public static final int VAR = 61;
  public static final int DOS_PUNTOS = 7;
  public static final int PACKAGE = 79;
  public static final int MAYQUE = 17;
  public static final int CLASS = 34;
  public static final int DIVIDIDO = 14;
  public static final int COMA = 10;
  public static final int SUPER = 54;
  public static final int ENTERO = 20;
  public static final int TRUE = 58;
  public static final int IGUAL = 29;
  public static final int EXTENDS = 43;
  public static final int MODULE = 69;
  public static final int DELETE = 39;
  public static final int DECIMAL = 21;
  public static final int BOOLEAN = 65;
  public static final int LLAVDER = 6;
  public static final int SWITCH = 55;
  public static final int DO = 40;
  public static final int FOR = 46;
  public static final int VOID = 62;
  public static final int PUBLIC = 82;
  public static final int RETURN = 53;
  public static final int PARDER = 4;
  public static final int CONCAT = 15;
  public static final int TRY = 59;
  public static final int MENOS = 12;
  public static final int MAS = 11;
  public static final int BREAK = 33;
  public static final int NULL = 51;
  public static final int EOF = 0;
  public static final int PUNTO = 8;
  public static final int THIS = 56;
  public static final int DEFAULT = 38;
  public static final int FUNCTION = 47;
  public static final int IMPORT = 48;
  public static final int RNUMERO = 26;
  public static final int DEBUGGER = 37;
  public static final int IGUALQUE = 18;
  public static final int IN = 49;
  public static final int SET = 71;
  public static final int error = 1;
  public static final int FINALLY = 45;
  public static final int CONTINUE = 36;
  public static final int INSTANCEOF = 50;
  public static final int OF = 75;
  public static final int UMENOS = 23;
  public static final int ANY = 64;
  public static final int CASE = 31;
  public static final int CADENA = 22;
  public static final int NEW = 52;
  public static final int STRING = 72;
  public static final int PRIVATE = 80;
  public static final int STATIC = 83;
  public static final int LET = 78;
  public static final int WITH = 63;
  public static final int RIMPRIMIR = 24;
  public static final int LLAVIZQ = 5;
}

