
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Oct 08 21:30:14 CDT 2022
//----------------------------------------------------

package back.analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IDENTIFICADOR = 82;
  public static final int AS = 62;
  public static final int DIVISION = 40;
  public static final int FROM = 60;
  public static final int TYPEOF = 33;
  public static final int TYPE = 59;
  public static final int IMPLEMENTS = 63;
  public static final int CONST = 6;
  public static final int PARENTESIS_CIERRE = 75;
  public static final int EXPORT = 14;
  public static final int GET = 53;
  public static final int MAYOR = 43;
  public static final int CONSTRUCTOR = 51;
  public static final int ENUM = 13;
  public static final int CATCH = 4;
  public static final int REQUIRE = 55;
  public static final int THROW = 30;
  public static final int COMILLA_SIMPLE = 80;
  public static final int DECLARE = 52;
  public static final int YIELD = 70;
  public static final int PROTECTED = 67;
  public static final int FALSE = 16;
  public static final int COMENTARIO = 84;
  public static final int IGUALIGUAL = 47;
  public static final int VAR = 34;
  public static final int DOS_PUNTOS = 88;
  public static final int PACKAGE = 65;
  public static final int PUNTO_COMA = 76;
  public static final int CLASS = 5;
  public static final int LOG = 79;
  public static final int LLAVE_CIERRE = 73;
  public static final int NUMBER = 56;
  public static final int COMA = 83;
  public static final int SUPER = 27;
  public static final int COMILLAS_DOBLES = 81;
  public static final int MODULO = 42;
  public static final int TRUE = 31;
  public static final int IGUAL = 86;
  public static final int WHILE = 36;
  public static final int EXTENDS = 15;
  public static final int MODULE = 54;
  public static final int DELETE = 10;
  public static final int BOOLEAN = 50;
  public static final int DIFERENTEDE = 48;
  public static final int SWITCH = 28;
  public static final int DO = 11;
  public static final int FOR = 18;
  public static final int VOID = 35;
  public static final int PUBLIC = 68;
  public static final int RETURN = 26;
  public static final int ELSE = 12;
  public static final int TRY = 32;
  public static final int MENOR = 44;
  public static final int BREAK = 2;
  public static final int STRING_LITERAL = 71;
  public static final int NULL = 25;
  public static final int EOF = 0;
  public static final int PUNTO = 77;
  public static final int THIS = 29;
  public static final int DEFAULT = 9;
  public static final int SUMA = 38;
  public static final int FUNCTION = 19;
  public static final int IMPORT = 21;
  public static final int CONSOLE = 78;
  public static final int MENORIGUAL = 45;
  public static final int LLAVE_APERTURA = 72;
  public static final int DEBUGGER = 8;
  public static final int IN = 22;
  public static final int SET = 57;
  public static final int error = 1;
  public static final int RESTA = 39;
  public static final int FINALLY = 17;
  public static final int CONTINUE = 7;
  public static final int IF = 20;
  public static final int INSTANCEOF = 23;
  public static final int NUMEROS = 87;
  public static final int OF = 61;
  public static final int PARENTESIS_APERTURA = 74;
  public static final int ANY = 49;
  public static final int MULTIPLICACION = 41;
  public static final int CASE = 3;
  public static final int MAYORIGUAL = 46;
  public static final int NEW = 24;
  public static final int STRING = 58;
  public static final int ESPACIO = 85;
  public static final int PRIVATE = 66;
  public static final int STATIC = 69;
  public static final int LET = 64;
  public static final int WITH = 37;
}

